# :computer: TEORIA 17 - EXCEPCIONES

## ¬°Hola! üëã Te damos la bienvenida a Excepciones.

Imag√≠nate que est√°s manejando un coche y repentinamente el motor deja de
funcionar. Es un problema grave, ¬øno? Ahora, piensa en tu coche como si fuera tu
programa. ¬øQu√© ocurre cuando hay un error durante su ejecuci√≥n? Necesitamos
una manera de manejar estos errores inesperados, como cuando el motor de un
coche falla. Y la buena noticia es que Java tiene una soluci√≥n para esto: las
excepciones. Ya hemos visto las excepciones cuando aprendimos estructuras de
control, pero ahora que sabemos mucho m√°s podemos profundizar m√°s sobre
su funcionamiento.

¬°Que comience el viaje! üöÄ

---

## :computer: Excepciones

En Java, una excepci√≥n es un evento que ocurre durante la ejecuci√≥n de un
programa y que interrumpe el flujo normal de instrucciones del programa. Esto
puede ser debido a un error en el c√≥digo, a problemas con los datos de entrada,
o a circunstancias imprevistas como una p√©rdida de conexi√≥n a la base de
datos.

---

## Palabras clave throw y throws

La primera vez que vimos las excepciones aprendimos que se capturen con el
bloque try catch.

```Java
public class Application {
  public static void main(String[] args) {
    try {
    Integer numero = 10/0;
  } catch (Exception e) {
    System.out.println("No puedes dividir por 0");
  }
  }
}
```

¬øPero qu√© sucede si ahora queremos lanzar una excepci√≥n para que sea
atrapada en otro lugar?, para eso podemos utilizar las palabras reservadas
throws y throw:

- **throw** se utiliza para lanzar una excepci√≥n expl√≠citamente en el c√≥digo. Se
usa en el cuerpo del m√©todo junto con el operador new.

- **throws** se utiliza para declarar que un m√©todo puede lanzar una
excepci√≥n. Se usa en la firma del m√©todo.

```Java
public class Application {
  public static void main(String[] args) throws Exception {
    metodoA();
    metodoB();
    metodoC();
  }
  public static void metodoA() throws Exception {
    try {
      Integer numero = 10/0;
    } catch (Exception e) {
      throw new Exception("No puedes dividir por 0");
    }
  }
  public static void metodoB() throws Exception {
    try {
      Integer numero = 10/0;
    } catch (Exception e) {
      throw e;
    }
  }
  public static void metodoC() throws Exception {
    throw new Exception("No puedes dividir por 0");
  }
}
```

Como puedes ver en el c√≥digo throw se utiliza tanto para lanzar una instancia
que ya existe como tambi√©n para lanzar una instancia nueva de Exception
pasandole un mensaje que luego puede ser recuperado con el m√©todo
getMessage() de la clase Exception. Tambi√©n no hace falta lanzar una excepci√≥n
dentro del bloque catch, en metodoC() lanzamos directamente la excepci√≥n en
el cuerpo del m√©todo.

La palabra throws se usa solo en la firma del m√©todo para se√±alar que lanza una
excepci√≥n que debe ser atrapada por en el bloque que invoca el m√©todo que
lanza la excepci√≥n, tambi√©n se puede volver a delegar el manejo de la excepci√≥n
volviendo a poner en la firma del m√©todo siguiente ‚Äúthrows Exception‚Äù, como en el
caso de nuestro ejemplo, donde en el m√©todo main en lugar de atrapar la
excepciones que pueden lanzar los m√©todos metodoA(), metodoB() y metodoC()
se vuelve a utilizar la cl√°usula throws.

Mira este video para entender mejor c√≥mo funcionan estas dos palabras:

[üëâExcepciones | Declaraci√≥n throw - throws | JAVA | Egg](https://www.youtube.com/watch?v=eOrZdCkn_Q8)

---

## Las excepciones y la herencia

En Java, todas las excepciones son subclases de la clase java.lang.Throwable.
Esta √∫ltima tiene dos subclases principales: Error y Exception.

## Clase Throwable:

- Atributos:

- detailMessage: Es el mensaje que describe porque se produjo el lanzamiento.

- M√©todos principales:

-getMessage(): Se utiliza para obtener eldetailMessage.

-printStackTrace(): Este m√©todo imprime en la consola la pila de llamadas que llev√≥ a la excepci√≥n. Es √∫til para depurar.

-getCause(): Retorna la causa de la excepci√≥n, el Throwable que caus√≥ esta excepci√≥n. Puede ser null si la causa no se conoce o no
se inicializ√≥.

-getStackTrace(): Retorna un array que contiene cada elemento en la pila de llamadas.

## Clase Error

La clase Error es utilizada por la JVM para indicar errores serios que no deber√≠an
intentar ser manejados por la aplicaci√≥n, a menudo son errores que suceden a
nivel de la m√°quina virtual de Java y est√°n m√°s all√° del control del c√≥digo que
estamos escribiendo. Algunos de los errores m√°s comunes son:

- OutOfMemoryError: Se lanza cuando la JVM no puede asignar m√°s memoria para un nuevo objeto debido a la falta de espacio de memoria.
Ejemplo de c√≥mo puede ocurrir:

```int[] matriz = new int[Integer.MAX_VALUE];```

- StackOverflowError: Se lanza cuando una aplicaci√≥n recursiva consume todo el espacio de la pila de llamadas. Ejemplo de c√≥mo puede ocurrir:

```Java
void funcionRecursiva() {
  funcionRecursiva();
}
```

## Clase Exception

Esta es la clase que normalmente se utiliza para manejar errores en nuestro
c√≥digo. Las subclases de Exception pueden ser Excepciones Marcadas (Checked
Exceptions) o no Marcadas (Unchecked Exceptions), y hablar√© m√°s sobre ellas en
un momento.

#### Las excepciones marcadas

Son aquellas que debes manejar siempre en tu c√≥digo. Son excepciones que se
espera que probablemente sucedan, por eso son marcadas y el compilador te
obliga a manejarlas de alguna manera. Por defecto, todas las Excepciones que
heredan de Exception son marcadas. Algunas de ellas son:

- IOException: Se lanza durante operaciones de entrada y salida
fallidas.

```JAva
try {
  BufferedReader lector = new BufferedReader(new
  FileReader("ruta/al/archivo"));
} catch (IOException e) {
  System.out.println("Ocurri√≥ un error al leer el archivo");
}
```

- ClassNotFoundException: Se lanza cuando intentamos cargar una
clase que no se encuentra.

```Java
try {
  Class.forName("ClaseNoExistente");
} catch (ClassNotFoundException e) {
  System.out.println("La clase no existe");
}
```

- InterruptedException: Se lanza cuando un hilo est√° esperando,
durmiendo, o de otra manera ocupado, y el hilo es interrumpido por
por otro hilo.

- FileNotFoundException: Se lanza cuando se intenta acceder a un
archivo que no existe.

```Java
try {
  new FileInputStream("archivo_no_existente.txt");
} catch (FileNotFoundException e) {
  System.out.println("Archivo no encontrado");
}
```

- SQLException: Se lanza cuando ocurre un error en una operaci√≥n de
Base de Datos.

```Java
try {
  // Supongamos que tienes un objeto de conexi√≥n "conexion"
  conexion.executeQuery("SELECT * from tabla_no_existente");
} catch (SQLException e) {
  System.out.println("Error en la consulta SQL");
}
```

---

## Las excepciones no marcadas

Son conocidas como RuntimeExceptions, son problemas que ocurren debido a
errores en el c√≥digo. Las RuntimeException son en su mayor√≠a bugs en el
programa, errores que son totalmente prevenibles si se escribe un buen c√≥digo.
Java no obliga a capturar estas excepciones ya que asume que como buenos
programadores, escribiremos c√≥digo que evite estas situaciones. Estas
excepciones se heredan de la clase ‚ÄúRuntimeException‚Äù. Algunas de ellas son:

- NullPointerException: Se lanza cuando se intenta acceder a un
miembro de un objeto nulo.

```Java
String str = null;
try {
  System.out.println(str.length());
} catch (NullPointerException e) {
  System.out.println("El objeto es nulo");
}
```

- ArrayIndexOutOfBoundsException: Se lanza cuando se intenta
acceder a un √≠ndice de un arreglo que no existe.

```Java
int[] arr = new int[5];
try {
  int numero = arr[10];
} catch (ArrayIndexOutOfBoundsException e) {
  System.out.println("El √≠ndice est√° fuera de los l√≠mites del arreglo");
}
```


- ArithmeticException: Se lanza cuando se intenta realizar una
operaci√≥n aritm√©tica ilegal, como dividir por cero.

```Java
try {
  int resultado = 10 / 0;
} catch (ArithmeticException e) {
  System.out.println("Divisi√≥n por cero");
}
```

- IllegalArgumentException: Se lanza cuando se pasa un argumento
ilegal o inapropiado a un m√©todo.

```Java
try {
  Thread.sleep(-1000);
} catch (IllegalArgumentException e) {
  System.out.println("Argumento ilegal");
}
```


- NumberFormatException: Se lanza cuando se intenta convertir un
String a un tipo num√©rico, pero el formato del String no es apropiado
para la conversi√≥n.
```Java
try {
  int num = Integer.parseInt("no_es_un_numero");
} catch (NumberFormatException e) {
  System.out.println("Formato de n√∫mero inv√°lido");
}
```

- ClassCastException: Se lanza cuando se intenta hacer un casting a
un tipo de dato que no es el correcto.
```Java
Object x = new Integer(0);
try {
  System.out.println((String)x);
} catch (ClassCastException e) {
  System.out.println("No se puede convertir a String");
}
```

- NegativeArraySizeException: Se lanza cuando se intenta crear un
array con un tama√±o negativo.
```Java
try {
  int[] arr = new int[-1];
} catch (NegativeArraySizeException e) {
  System.out.println("El tama√±o del arreglo no puede ser negativo");
}
```

- StringIndexOutOfBoundsException: Se lanza cuando se intenta
acceder a un √≠ndice de un String que no existe.

```Java
String str = "Hola";
try {
  char ch = str.charAt(10);
} catch (StringIndexOutOfBoundsException e) {
  System.out.println("√çndice fuera de los l√≠mites del String");
}
```

---

## Bloque finally y try with resources

El bloque finally se utiliza para ejecutar c√≥digo importante como la limpieza de
recursos, no importa si una excepci√≥n fue lanzada o no. Siempre se ejecuta.

```Java
public class Main {
  public static void main(String[] args) {
  try {
    // C√≥digo que puede lanzar una excepci√≥n
  } catch (Exception e) {
    // Manejar la excepci√≥n
  } finally {
    // Limpiar recursos
    }
  }
}
```

Java 7 introdujo una nueva caracter√≠stica llamada try-with-resources que
permite una mejor gesti√≥n de los recursos que se utilizan en un bloque try,
asegurando que estos recursos se cierren al finalizar el proceso, incluso si se
produce una excepci√≥n.

```Java
public class Main {
  public static void main(String[] args) {
    try (FileReader fr = new FileReader("file path")) {
      // Utilizar el recurso
    } catch (IOException e) {
      // Manejar la excepci√≥n
    }
  }
}
```


En este caso, el recurso FileReader se cerrar√° autom√°ticamente despu√©s del
bloque try, lo que lo hace m√°s eficiente que el uso
